#!/bin/bash
if [[ $0 =~ ^(.*)/([^/]+)$ ]]; then
	WORKDIR="${BASH_REMATCH[1]}"
	CALLED="${BASH_REMATCH[2]}"
fi

# launch & persist (run + exec)
#if [[ -n "$1" ]]; then
	case "${1}" in
		'stop') ## list commands
			printf "[apnex/${CALLED}] stopping\n" 1>&2
			docker rm -f ${CALLED} 2>/dev/null
		;;
		*) ## cleanup stopped - then launch + persist (run + exec)
			docker rm -v $(docker ps -qa -f name=${CALLED} -f status=exited) 2>/dev/null
			RUNNING=$(docker ps -q -f name="${CALLED}")
			if [[ -z "$RUNNING" ]]; then
				printf "[apnex/${CALLED}] not running - now starting\n" 1>&2
				docker run -id --name ${CALLED} -e VMWUSER -e VMWPASS -v ${PWD}:/files --entrypoint=/bin/sh apnex/${CALLED} 1>&2
			fi
			RUNNING=$(docker ps -q -f name="${CALLED}")
			if [[ -n "$RUNNING" ]]; then
				docker exec -t ${CALLED} ${CALLED} "${@}"
			fi
		;;
	esac
#fi
